FC_vars = {'WASI Matrix Reasoning':'WASI - Matrix Reasoning Percentile:',
 'ROWPVT-4':'ROWPVT-4 Percentile:',
 'CVLT-C Trial 1':'CVLT-C Trial 1 Percentile:',
 'WISC-IV Digit Span Forward':'WISC-V - Digit Span Forward Percentile:',
 'WISC-IV Spatial Span Forward':'WISC-IV - Spatial Span Forward Percentile:',
 'WISC-IV Digit Span Backward':'WISC-V - Digit Span Backward Percentile:',
 'WISC-IV Spatial Span Backward':'WISC-IV - Spatial Span Backward Percentile:',
 'NEPSY-II Naming':'NEPSY-II - Naming Percentile:',
 'WISC-IV Symbol Search':'WISC-IV - Symbol Search Percentile:',
 "Children's Colored Trails A":"Children's Colored Trails A Percentile:",
 'CVLT-C Trial 5':'CVLT-C Trial 5 Percentile:',
 'CVLT-C SDFR':'CVLT-C SDFR Percentile:',
 'CVLT-C LDFR':'CVLT-C LDFR Percentile:',
 'Rey-O Delay':'Rey-O Delay Percentile:',
 'Judgment of Line Orientation':'Judgment of Line Orientation Percentile:',
 'Beery VMI':'Beery VMI Percentile:',
 'WISC-IV Coding':'WISC-IV - Coding Percentile:',
 'NEPSY-II Semantic Fluency':'NEPSY-II - Semantic Fluency Percentile:',
 'NEPSY-II Phonemic Fluency':'NEPSY-II - Phonemic Fluency Percentile:',
 'DKEFS Design Fluency Filled':'DKEFS - Design Fluency Filled Percentile:',
 'NEPSY-II Inhibition':'NEPSY-II - Inhibition Percentile:',
 'NEPSY-II Switching':'NEPSY-II - Switching Percentile:',
 "Children's Colored Trails B":"Children's Colored Trails B Percentile:",
 'WCJ Segmentation':'Woodcock Johnson Test of Oral Language (Test 3) Segmentation Percentile:',
 'WCJ Sound Blending':'Woodcock Johnson Test of Oral Language (Test 7) Sound Blending Percentile:',
 'WCJ Sound Awareness':'Woodcock Johnson Test of Oral Language (Test 9) Sound Awareness Percentile:',
 'WCJ Nonword Repetition':'Woodcock Johnson Test of Cognitive Abilities (Test 12) Nonword Repetition Percentile:',
 'WCJ Memory for Words':'Woodcock Johnson Test of Cognitive Abilities (Test 18) Memory for Words Percentile:',
 'WCJ Sentence Repetition':'Woodcock Johnson Test of Oral Language (Test 5) Sentence Repetition Percentile:',
 'WCJ Rapid Picture Naming':'Woodcock Johnson Test of Oral Language (Test 4) Rapid Picture Naming Percentile:',
 'WCJ Letter-Word Identification':'Woodcock Johnson Test of Achievement (Test 1) Letter-Word Identification Percentile:',
 'WCJ Word Attack':'Woodcock Johnson Test of Achievement (Test 7) Word Attack Percentile:',
 'TOWRE-2 Sight Word Efficiency':'TOWRE-2 (Subtest 1) Sight Word Efficiency Percentile:',
 'TOWRE-2 Phonemic Decoding Efficiency':'TOWRE-2 (Subtest 2) Phonemic Decoding Efficiency Percentile:',
 'GORT-5 Rate':'GORT-5 Rate Percentile:',
 'GORT-5 Accuracy':'GORT-5 Accuracy Percentile:',
 'GORT-5 Comprehension':'GORT-5 Comprehension Percentile:',
 'WCJ Spelling of Sounds':'Woodcock Johnson Test of Achievement (Test 16) Spelling of Sounds Percentile:',
 'WCJ Spelling':'Woodcock Johnson Test of Achievement (Test 3) Spelling Percentile:',
 'WCJ Calculations':'Woodcock Johnson Test of Achievement (Test 5) Calculations Percentile:'}


FC_vars_select = {'WASI Matrix Reasoning':'WASI - Matrix Reasoning Percentile:',
 'WISC-IV Digit Span Forward':'WISC-V - Digit Span Forward Percentile:',
 'WISC-IV Digit Span Backward':'WISC-V - Digit Span Backward Percentile:',
 'NEPSY-II Naming':'NEPSY-II - Naming Percentile:',
 "Children's Colored Trails A":"Children's Colored Trails A Percentile:",
 'Rey-O Delay':'Rey-O Delay Percentile:',
 'Judgment of Line Orientation':'Judgment of Line Orientation Percentile:',
 'NEPSY-II Semantic Fluency':'NEPSY-II - Semantic Fluency Percentile:',
 'NEPSY-II Phonemic Fluency':'NEPSY-II - Phonemic Fluency Percentile:',
 'NEPSY-II Inhibition':'NEPSY-II - Inhibition Percentile:',
 'NEPSY-II Switching':'NEPSY-II - Switching Percentile:',
 "Children's Colored Trails B":"Children's Colored Trails B Percentile:",
 'WCJ Segmentation':'Woodcock Johnson Test of Oral Language (Test 3) Segmentation Percentile:',
 'WCJ Sound Blending':'Woodcock Johnson Test of Oral Language (Test 7) Sound Blending Percentile:',
 'WCJ Sound Awareness':'Woodcock Johnson Test of Oral Language (Test 9) Sound Awareness Percentile:',
 'WCJ Nonword Repetition':'Woodcock Johnson Test of Cognitive Abilities (Test 12) Nonword Repetition Percentile:',
 'WCJ Memory for Words':'Woodcock Johnson Test of Cognitive Abilities (Test 18) Memory for Words Percentile:',
 'WCJ Sentence Repetition':'Woodcock Johnson Test of Oral Language (Test 5) Sentence Repetition Percentile:',
 'WCJ Rapid Picture Naming':'Woodcock Johnson Test of Oral Language (Test 4) Rapid Picture Naming Percentile:',
 'WCJ Letter-Word Identification':'Woodcock Johnson Test of Achievement (Test 1) Letter-Word Identification Percentile:',
 'WCJ Word Attack':'Woodcock Johnson Test of Achievement (Test 7) Word Attack Percentile:',
 'TOWRE-2 Sight Word Efficiency':'TOWRE-2 (Subtest 1) Sight Word Efficiency Percentile:',
 'TOWRE-2 Phonemic Decoding Efficiency':'TOWRE-2 (Subtest 2) Phonemic Decoding Efficiency Percentile:',
 'GORT-5 Rate':'GORT-5 Rate Percentile:',
 'GORT-5 Accuracy':'GORT-5 Accuracy Percentile:',
 'GORT-5 Comprehension':'GORT-5 Comprehension Percentile:'}