FC_vars = {'WASI Matrix Reasoning':'WASI - Matrix Reasoning Percentile:',
 'ROWPVT-4':'ROWPVT-4 Percentile:',
 'CVLT-C Trial 1':'CVLT-C Trial 1 Percentile:',
 'WISC-IV Digit Span Forward':'WISC-IV - Digit Span Forward Percentile:',
 'WISC-IV Spatial Span Forward':'WISC-IV - Spatial Span Forward Percentile:',
 'WISC-IV Digit Span Backward':'WISC-IV - Digit Span Backward Percentile:',
 'WISC-IV Spatial Span Backward':'WISC-IV - Spatial Span Backward Percentile:',
 'NEPSY-II Naming':'NEPSY-II - Naming Percentile:',
 'WISC-IV Symbol Search':'WISC-IV - Symbol Search Percentile:',
 "Children's Colored Trails A":"Children's Colored Trails A Percentile:",
 'CVLT-C Trial 5':'CVLT-C Trial 5 Percentile:',
 'CVLT-C SDFR':'CVLT-C SDFR Percentile:',
 'CVLT-C LDFR':'CVLT-C LDFR Percentile:',
 'Rey-O Delay':'Rey-O Delay Percentile:',
 'Judgment of Line Orientation':'Judgment of Line Orientation Percentile:',
 'Beery VMI':'Beery VMI Percentile:',
 'WISC-IV Coding':'WISC-IV - Coding Percentile:',
 'NEPSY-II Semantic Fluency':'NEPSY-II - Semantic Fluency Percentile:',
 'NEPSY-II Phonemic Fluency':'NEPSY-II - Phonemic Fluency Percentile:',
 'DKEFS Design Fluency Filled':'DKEFS - Design Fluency Filled Percentile:',
 'NEPSY-II Inhibition':'NEPSY-II - Inhibition Percentile:',
 'NEPSY-II Switching':'NEPSY-II - Switching Percentile:',
 "Children's Colored Trails B":"Children's Colored Trails B Percentile:",
 'WCJ Segmentation':'Woodcock Johnson Test of Oral Language (Test 3) Segmentation Percentile:',
 'WCJ Sound Blending':'Woodcock Johnson Test of Oral Language (Test 7) Sound Blending Percentile:',
 'WCJ Sound Awareness':'Woodcock Johnson Test of Oral Language (Test 9) Sound Awareness Percentile:',
 'WCJ Nonword Repetition':'Woodcock Johnson Test of Cognitive Abilities (Test 12) Nonword Repetition Percentile:',
 'WCJ Memory for Words':'Woodcock Johnson Test of Cognitive Abilities (Test 18) Memory for Words Percentile:',
 'WCJ Sentence Repetition':'Woodcock Johnson Test of Oral Language (Test 5) Sentence Repetition Percentile:',
 'WCJ Rapid Picture Naming':'Woodcock Johnson Test of Oral Language (Test 4) Rapid Picture Naming Percentile:',
 'WCJ Letter-Word Identification':'Woodcock Johnson Test of Achievement (Test 1) Letter-Word Identification Percentile:',
 'WCJ Word Attack':'Woodcock Johnson Test of Achievement (Test 7) Word Attack Percentile:',
 'TOWRE-2 Sight Word Efficiency':'TOWRE-2 (Subtest 1) Sight Word Efficiency Percentile:',
 'TOWRE-2 Phonemic Decoding Efficiency':'TOWRE-2 (Subtest 2) Phonemic Decoding Efficiency Percentile:',
 'GORT-5 Rate':'GORT-5 Rate Percentile:',
 'GORT-5 Accuracy':'GORT-5 Accuracy Percentile:',
 'GORT-5 Comprehension':'GORT-5 Comprehension Percentile:',
 'WCJ Spelling of Sounds':'Woodcock Johnson Test of Achievement (Test 16) Spelling of Sounds Percentile:',
 'WCJ Spelling':'Woodcock Johnson Test of Achievement (Test 3) Spelling Percentile:',
 'WCJ Calculations':'Woodcock Johnson Test of Achievement (Test 5) Calculations Percentile:'
 }

FC_vars_labels = {'mat_r_per': 'WASI Matrix Reasoning',
        'rowpvt_percentile': 'ROWPVT-4',
        'cvlt_trial1_percentile': 'CVLT-C Trial 1',
        'digitforward_percentile': 'WISC-IV Digit Span Forward',
        'spatialforward_percentile': 'WISC-IV Spatial Span Forward',
        'digitbackward_percentile': 'WISC-IV Digit Span Backward',
        'spatialbackward_percentile': 'WISC-IV Spatial Span Backward',
        'naming_per': 'NEPSY-II Naming',
        'sym_search_perc': 'WISC-IV Symbol Search',
        'color_ta_per': "Children's Colored Trails A",
        'cvlt_trial5_percentile': 'CVLT-C Trial 5',
        'cvltc_sdfr_percentile': 'CVLT-C SDFR',
        'cvltc_ldfr_percentile': 'CVLT-C LDFR',
        'rey_delay_percentile': 'Rey-O Delay',
        'jolo_percentile': 'Judgment of Line Orientation',
        'beery_percentile': 'Beery VMI',
        'coding_percentile': 'WISC-IV Coding',
        'semanticfluency_percentile': 'NEPSY-II Semantic Fluency',
        'phonfluency_percentile': 'NEPSY-II Phonemic Fluency',
        'dkefs_df_filled_perc': 'DKEFS Design Fluency Filled',
        'inhib_perc': 'NEPSY-II Inhibition',
        'switching_perc': 'NEPSY-II Switching',
        'color_tb_per': "Children's Colored Trails B",
        'wj_seg_per': 'WCJ Segmentation',
        'wj_soundblend_per': 'WCJ Sound Blending',
        'wj_soundawareness_per': 'WCJ Sound Awareness',
        'wj_nonwordrep_per': 'WCJ Nonword Repetition',
        'wj_memwords_perc': 'WCJ Memory for Words',
        'wj_sentrep_perc': 'WCJ Sentence Repetition',
        'wj_rapnaming_per': 'WCJ Rapid Picture Naming',
        'wj_lw_per': 'WCJ Letter-Word Identification',
        'wj_wordattack_per': 'WCJ Word Attack',
        'towre_sde_per': 'TOWRE-2 Sight Word Efficiency',
        'towre_pde_per': 'TOWRE-2 Phonemic Decoding Efficiency',
        'rate_percentile': 'GORT-5 Rate',
        'accuracy_percentile': 'GORT-5 Accuracy',
        'comp_percentile': 'GORT-5 Comprehension',
        'wj_spellingsounds_per': 'WCJ Spelling of Sounds',
        'wj_spelling_per': 'WCJ Spelling',
        'wj_calc_per': 'WCJ Calculations'
 }


FC_neuropsych_dict = {'Reasoning Estimates': ['mat_r_per', 'wiscv_figweight_per', 'rowpvt_percentile', 'wj_oral_perc'],
              'Registration & Working Memory': ['digitforward_percentile', 'digitbackward_percentile', 'spatialforward_percentile', 'spatialbackward_percentile'],
              'Processing Speed': ['naming_per', 'sym_search_perc', 'color_ta_per', 'coding_percentile'],
              'Learning & Memory': ['cvlt_trial1_percentile', 'cvlt_trial5_percentile', 'cvltc_ldfr_percentile', 'rey_delay_percentile'],
              'Visuospatial/Visuomotor':['beery_percentile', 'jolo_percentile', 'wiscv_vispuzzle_per'],
              'Executive Functioning': ['phonfluency_percentile', 'dkefs_df_filled_perc', 'color_tb_per', 'inhib_perc', 'switching_perc']
}

FC_language_dict = {'Phonology': ['wj_seg_per', 'wj_soundblend_per', 'wj_soundawareness_per'],
                     'Phonological Loop': ['wj_nonwordrep_per', 'wj_memwords_perc'],
                     'Semantic Impact': ['wj_sentrep_perc', 'semanticfluency_percentile'],
                     'Rapid Naming': ['wj_rapnaming_per'],
                     'Reading': ['wj_lw_per', 'wj_wordattack_per', 'towre_sde_per', 'towre_pde_per', 
                                 'rate_percentile', 'accuracy_percentile', 'fluency_percentile', 'comp_percentile',
                                 'ktea_read_percentile', 'ktea_listen_percentile'],
                    'Spelling': ['wj_spelling_per', 'wj_spellingsounds_per'],
                    'Calculations': ['wj_calc_per']
}

FC_language_supp_dict = ['morph_tot', 'ppt25_pic']

# math_chart = {'Number Processing':['dsb2_verb_num_pe', 'dsb2_num_verb_r_pe', 'dsb2_num_verb_w_pe', 'dsb2_count_f_pe',
#                 'dsb2_count_b_pe', 'dsb2_compa_int_pe', 'dsb2_compa_frac_pe', 'dsb2_compa_dec_pe','dsb2_numb_line_no_pe',
#                 'dsb2_numb_line_lo_pe', 'dsb2_numb_line_lp_pe'],
#               'Arithmetic Facts':['dsb2_add_fact_pe', 'dsb2_ment_add_pe', 'dsb2_sub_fact_pe', 'dsb2_ment_sub_pe',
#                 'dsb2_mult_fact_pe', 'dsb2_mult_table_pe', 'dsb2_comp_addsub_pe', 'dsb2_comp_multdiv_pe'],
#               'Other':
#                 ['dsb2_equiv_frac_pe',
#                 'dsb2_seq_pe',
#                 'dsb2_word_prob_pe',
#                 'dsb2_simpli_pe',
#                 'dsb2_equat_pe',
#                 'dsb2_perim_raw',
#                 'dsb2_perim_max',
#                 'dsb2_perim_pe',
#                 'dsb2_perim_time',
#                 'dsb2_area_pe',
#                 'dsb2_model_pe',
#                 'dsb2_visuo_repro_pe',
#                 'dsb2_visuo_recog_pe']}

FC_vars_select = {'WASI Matrix Reasoning':'WASI - Matrix Reasoning Percentile:',
 'WISC-IV Digit Span Forward':'WISC-V - Digit Span Forward Percentile:',
 'WISC-IV Digit Span Backward':'WISC-V - Digit Span Backward Percentile:',
 'NEPSY-II Naming':'NEPSY-II - Naming Percentile:',
 "Children's Colored Trails A":"Children's Colored Trails A Percentile:",
 'Rey-O Delay':'Rey-O Delay Percentile:',
 'Judgment of Line Orientation':'Judgment of Line Orientation Percentile:',
 'NEPSY-II Semantic Fluency':'NEPSY-II - Semantic Fluency Percentile:',
 'NEPSY-II Phonemic Fluency':'NEPSY-II - Phonemic Fluency Percentile:',
 'NEPSY-II Inhibition':'NEPSY-II - Inhibition Percentile:',
 'NEPSY-II Switching':'NEPSY-II - Switching Percentile:',
 "Children's Colored Trails B":"Children's Colored Trails B Percentile:",
 'WCJ Segmentation':'Woodcock Johnson Test of Oral Language (Test 3) Segmentation Percentile:',
 'WCJ Sound Blending':'Woodcock Johnson Test of Oral Language (Test 7) Sound Blending Percentile:',
 'WCJ Sound Awareness':'Woodcock Johnson Test of Oral Language (Test 9) Sound Awareness Percentile:',
 'WCJ Nonword Repetition':'Woodcock Johnson Test of Cognitive Abilities (Test 12) Nonword Repetition Percentile:',
 'WCJ Memory for Words':'Woodcock Johnson Test of Cognitive Abilities (Test 18) Memory for Words Percentile:',
 'WCJ Sentence Repetition':'Woodcock Johnson Test of Oral Language (Test 5) Sentence Repetition Percentile:',
 'WCJ Rapid Picture Naming':'Woodcock Johnson Test of Oral Language (Test 4) Rapid Picture Naming Percentile:',
 'WCJ Letter-Word Identification':'Woodcock Johnson Test of Achievement (Test 1) Letter-Word Identification Percentile:',
 'WCJ Word Attack':'Woodcock Johnson Test of Achievement (Test 7) Word Attack Percentile:',
 'TOWRE-2 Sight Word Efficiency':'TOWRE-2 (Subtest 1) Sight Word Efficiency Percentile:',
 'TOWRE-2 Phonemic Decoding Efficiency':'TOWRE-2 (Subtest 2) Phonemic Decoding Efficiency Percentile:',
 'GORT-5 Rate':'GORT-5 Rate Percentile:',
 'GORT-5 Accuracy':'GORT-5 Accuracy Percentile:',
 'GORT-5 Comprehension':'GORT-5 Comprehension Percentile:'}